package com.xworkz.interfaceex2.runner;

import com.xworkz.interfaceex2.BackEnd;
import com.xworkz.interfaceex2.CNN;
import com.xworkz.interfaceex2.FrontEnd;
import com.xworkz.interfaceex2.Project;

public class ProjectRunner {
    public static void main(String[] args) {
        Project project=new FrontEnd();
        project.apiDetails();
        project.backendDetails();
        project.projectDetails();
        project.duration();
        project.frontEndDetails();
        project.finalReport();
        project.phase2Info();
        project.requirement();
        project.softwareDetails();
        project.plase1Report();
        project.titileInfo();
        project.teamsizedetils();
        project.teamMemmbersDetails();
        project.teamDeatils();
        project.synoposisInfo();
        project.synopisreport();
        FrontEnd.collegeDetails();
        FrontEnd.departmentDetails();
        FrontEnd.guideDetails();
        FrontEnd.hardwareDettails();
        FrontEnd.mentorDetails();
        System.out.println("-------------------------------------------------------");

        Project project1=new FrontEnd();
        project1.apiDetails();
        project1.backendDetails();
        project1.projectDetails();
        project1.duration();
        project1.frontEndDetails();
        project1.finalReport();
        project1.phase2Info();
        project1.requirement();
        project1.softwareDetails();
        project1.plase1Report();
        project1.titileInfo();
        project1.teamsizedetils();
        project1.teamMemmbersDetails();
        project1.teamDeatils();
        project1.synoposisInfo();
        project1.synopisreport();
        FrontEnd.collegeDetails();
        FrontEnd.departmentDetails();
        FrontEnd.guideDetails();
        FrontEnd.hardwareDettails();
        FrontEnd.mentorDetails();
        System.out.println("-------------------------------------------------------");

        Project project2=new FrontEnd();
        project2.apiDetails();
        project2.backendDetails();
        project2.projectDetails();
        project2.duration();
        project2.frontEndDetails();
        project2.finalReport();
        project2.phase2Info();
        project2.requirement();
        project2.softwareDetails();
        project2.plase1Report();
        project2.titileInfo();
        project2.teamsizedetils();
        project2.teamMemmbersDetails();
        project2.teamDeatils();
        project2.synoposisInfo();
        project2.synopisreport();
        FrontEnd.collegeDetails();
        FrontEnd.departmentDetails();
        FrontEnd.guideDetails();
        FrontEnd.hardwareDettails();
        FrontEnd.mentorDetails();
        System.out.println("-------------------------------------------------------");

        Project project3=new BackEnd();
        project3.apiDetails();
        project3.backendDetails();
        project3.projectDetails();
        project3.duration();
        project3.frontEndDetails();
        project3.finalReport();
        project3.phase2Info();
        project3.requirement();
        project3.softwareDetails();
        project3.plase1Report();
        project3.titileInfo();
        project3.teamsizedetils();
        project3.teamMemmbersDetails();
        project3.teamDeatils();
        project3.synoposisInfo();
        project3.synopisreport();
        BackEnd.collegeDetails();
        BackEnd.departmentDetails();
        BackEnd.guideDetails();
        BackEnd.hardwareDettails();
        BackEnd.mentorDetails();
        System.out.println("-------------------------------------------------------");

        Project project4=new BackEnd();
        project4.apiDetails();
        project4.backendDetails();
        project4.projectDetails();
        project4.duration();
        project4.frontEndDetails();
        project4.finalReport();
        project4.phase2Info();
        project4.requirement();
        project4.softwareDetails();
        project4.plase1Report();
        project4.titileInfo();
        project4.teamsizedetils();
        project4.teamMemmbersDetails();
        project4.teamDeatils();
        project4.synoposisInfo();
        project4.synopisreport();
        BackEnd.collegeDetails();
        BackEnd.departmentDetails();
        BackEnd.guideDetails();
        BackEnd.hardwareDettails();
        BackEnd.mentorDetails();
        System.out.println("-------------------------------------------------------");

        Project project5=new BackEnd();
        project5.apiDetails();
        project5.backendDetails();
        project5.projectDetails();
        project5.duration();
        project5.frontEndDetails();
        project5.finalReport();
        project5.phase2Info();
        project5.requirement();
        project5.softwareDetails();
        project5.plase1Report();
        project5.titileInfo();
        project5.teamsizedetils();
        project5.teamMemmbersDetails();
        project5.teamDeatils();
        project5.synoposisInfo();
        project5.synopisreport();
        BackEnd.collegeDetails();
        BackEnd.departmentDetails();
        BackEnd.guideDetails();
        BackEnd.hardwareDettails();
        BackEnd.mentorDetails();
        System.out.println("-------------------------------------------------------");

        Project project6=new CNN();
        project6.apiDetails();
        project6.backendDetails();
        project6.projectDetails();
        project6.duration();
        project6.frontEndDetails();
        project6.finalReport();
        project6.phase2Info();
        project6.requirement();
        project6.softwareDetails();
        project6.plase1Report();
        project6.titileInfo();
        project6.teamsizedetils();
        project6.teamMemmbersDetails();
        project6.teamDeatils();
        project6.synoposisInfo();
        project6.synopisreport();
        CNN.collegeDetails();
        CNN.departmentDetails();
        CNN.guideDetails();
        CNN.hardwareDettails();
        CNN.mentorDetails();
        System.out.println("-------------------------------------------------------");

        Project project7=new CNN();
        project7.apiDetails();
        project7.backendDetails();
        project7.projectDetails();
        project7.duration();
        project7.frontEndDetails();
        project7.finalReport();
        project7.phase2Info();
        project7.requirement();
        project7.softwareDetails();
        project7.plase1Report();
        project7.titileInfo();
        project7.teamsizedetils();
        project7.teamMemmbersDetails();
        project7.teamDeatils();
        project7.synoposisInfo();
        project7.synopisreport();
        CNN.collegeDetails();
        CNN.departmentDetails();
        CNN.guideDetails();
        CNN.hardwareDettails();
        CNN.mentorDetails();
        System.out.println("-------------------------------------------------------");

        Project project8=new CNN();
        project8.apiDetails();
        project8.backendDetails();
        project8.projectDetails();
        project8.duration();
        project8.frontEndDetails();
        project8.finalReport();
        project8.phase2Info();
        project8.requirement();
        project8.softwareDetails();
        project8.plase1Report();
        project8.titileInfo();
        project8.teamsizedetils();
        project8.teamMemmbersDetails();
        project8.teamDeatils();
        project8.synoposisInfo();
        project8.synopisreport();
        CNN.collegeDetails();
        CNN.departmentDetails();
        CNN.guideDetails();
        CNN.hardwareDettails();
        CNN.mentorDetails();
        System.out.println("-------------------------------------------------------");
    }
}
